import { Artwork, Testimonial } from '@/types';

export const ARTWORKS: Artwork[] = [
  {
    id: 'art-1',
    title: 'Whispers of the Horizon',
    artist: 'Marcus Vance',
    category: 'Paintings',
    price: 3200,
    dimensions: '36" x 48"',
    medium: 'Oil and Gold Leaf on Linen',
    year: 2026,
    image: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?auto=format&fit=crop&q=80&w=800',
    description: 'An evocative abstract landscape exploring the boundary between light and shadow, highlighted by hand-applied 24k gold leaf details.',
    featured: true,
    slug: 'whispers-of-horizon',
  },
  {
    id: 'art-2',
    title: 'Echoes of Silence',
    artist: 'Elena Rostova',
    category: 'Paintings',
    price: 2400,
    dimensions: '24" x 36"',
    medium: 'Acrylic and Mixed Media on Canvas',
    year: 2025,
    image: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?auto=format&fit=crop&q=80&w=800',
    description: 'A structural exploration of monochromatic texture, creating deep depth through physical layering of organic materials.',
    featured: true,
    slug: 'echoes-of-silence',
  },
  {
    id: 'art-3',
    title: 'Syllables of the Wind',
    artist: 'Kaito Hayashi',
    category: 'Calligraphy',
    price: 1200,
    dimensions: '18" x 24"',
    medium: 'Sumi Ink on Handmade Mulberry Paper',
    year: 2026,
    image: 'https://images.unsplash.com/photo-1579783928621-7a13d66a6211?auto=format&fit=crop&q=80&w=800',
    description: 'A breathtaking contemporary calligraphy piece representing the flow of natural breezes through minimal ink gestures.',
    featured: true,
    slug: 'syllables-of-the-wind',
  },
  {
    id: 'art-4',
    title: 'Mindfulness in Stroke',
    artist: 'Kaito Hayashi',
    category: 'Calligraphy',
    price: 950,
    dimensions: '16" x 20"',
    medium: 'Traditional Charcoal Ink on Heavy Rice Paper',
    year: 2025,
    image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&q=80&w=800',
    description: 'A meditative single-stroke calligraphy artwork meant to bring calm and focus to modern architectural spaces.',
    featured: false,
    slug: 'mindfulness-in-stroke',
  },
  {
    id: 'art-5',
    title: 'Anatomy of Light',
    artist: 'Diana Prince',
    category: 'Sketches',
    price: 850,
    dimensions: '12" x 16"',
    medium: 'Graphite and Charcoal on Acid-Free Board',
    year: 2026,
    image: 'https://images.unsplash.com/photo-1580136579312-94651dfd596d?auto=format&fit=crop&q=80&w=800',
    description: 'An architectural study of arches and classical light forms, displaying incredible contrast and detail.',
    featured: true,
    slug: 'anatomy-of-light',
  },
  {
    id: 'art-6',
    title: 'Geometry of Solitude',
    artist: 'Diana Prince',
    category: 'Sketches',
    price: 600,
    dimensions: '11" x 14"',
    medium: 'Silverpoint and Graphite on Paper',
    year: 2025,
    image: 'https://images.unsplash.com/photo-1605721911519-3dfeb3be25e7?auto=format&fit=crop&q=80&w=800',
    description: 'A delicate sketch capturing modern structural intersections through fine line-weights and geometric shadows.',
    featured: false,
    slug: 'geometry-of-solitude',
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: 'test-1',
    name: 'Alexandra Sterling',
    role: 'Private Collector',
    quote: 'The quality of the curation at AURA is exceptional. The original painting I ordered arrived in perfect museum conditions, and the custom frame exceeds expectations.',
    rating: 5,
  },
  {
    id: 'test-2',
    name: 'Julian Mercer',
    role: 'Interior Architect',
    quote: 'For our high-end residential projects, AURA is our secret weapon. Their custom commissions fit our bespoke spaces beautifully, and the process is seamless.',
    rating: 5,
  },
];
